# Unified CI for Tasklist. Runs backend unit tests, front end unit tests, backup restore tests on ES and OS, and docker tests
# test location: /tasklist, tasklist/qa/backup-restore-tests, tasklist/qa/integration-tests
# called by: ci.yml
# type: CI
# owner: @camunda/core-features
name: Tasklist CI

on:
  workflow_dispatch:
    inputs:
      runFeTests:
        description: "Set to true to run front end tests for Tasklist"
        type: boolean
        required: true
      runBeTests:
        description: "Set to true to run back end tests for Tasklist"
        type: boolean
        required: true
  workflow_call:
    inputs:
      runFeTests:
        description: "Set to true if Tasklist front-end code was changed"
        type: boolean
        required: true
      runBeTests:
        description: "Set to true if Tasklist back-end code was changed"
        type: boolean
        required: true

defaults:
  run:
    # use bash shell by default to ensure pipefail behavior is the default
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

env:
  GHA_BEST_PRACTICES_LINTER: enabled

jobs:
  # run this test every time the workflow is triggered
  tasklist-backend-unit-tests:
    name: "[UT] Back End / ${{matrix.suiteName}}"
    uses: ./.github/workflows/ci-webapp-run-ut-reuseable.yml
    permissions: { }  # GITHUB_TOKEN unused in this job
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        suite: [ DataLayer, CoreFeatures ]
        include:
          - suite: DataLayer
            suiteName: Data Layer
          - suite: CoreFeatures
            suiteName: Core Features
    with:
      componentName: "Tasklist"
      suite: ${{ matrix.suite }}
      suiteName: ${{ matrix.suiteName }}

  tasklist-frontend-tests:
    name: "[UT] Front End"
    if: inputs.runFeTests
    uses: ./.github/workflows/tasklist-ci-fe-reusable.yml
    secrets: inherit
    permissions: { }  # GITHUB_TOKEN unused in this job

  elasticsearch:
    name: "[IT] ElasticSearch Backup Restore / Data Layer"
    if: inputs.runBeTests
    permissions: { }  # GITHUB_TOKEN unused in this job
    uses: ./.github/workflows/tasklist-backup-restore-tests-reusable.yml
    secrets: inherit
    with:
      database: elasticsearch

  opensearch:
    name: "[IT] OpenSearch Backup Restore / Data Layer"
    if: inputs.runBeTests
    permissions: { }  # GITHUB_TOKEN unused in this job
    uses: ./.github/workflows/tasklist-backup-restore-tests-reusable.yml
    secrets: inherit
    with:
      database: opensearch

  tasklist-docker-tests:
    # Currently only runs Tasklist Docker tests but should be extended in future to also include backend tests
    name: "[IT] Docker Tests / Core Features"
    if: inputs.runBeTests
    uses: ./.github/workflows/tasklist-docker-tests.yml
    secrets: inherit
    permissions: { }  # GITHUB_TOKEN unused in this job
