# description: Workflow for running Front End tests for Tasklist. Does a type check, two lint checks (eslint and stylelint), unit tests, visual regression tests, and accessibility testing (a11y)
# test location: /tasklist/client
# called by: ci.yml
# type: CI
# owner: @camunda/core-features
name: Tasklist Frontend Jobs

on:
  workflow_call: {}

env:
  GHA_BEST_PRACTICES_LINTER: enabled

jobs:
  fe-type-check:
    name: "Type check / Core Features"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: tasklist/client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
        name: Install dependencies
      - run: npm run ts-check
        name: Type checks
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"

  fe-eslint:
    name: "ESLint / Core Features"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: tasklist/client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
        name: Install dependencies
      - run: npm run eslint
        name: ESLint
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"

  fe-stylelint:
    name: "Stylelint / Core Features"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: tasklist/client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
        name: Install dependencies
      - run: npm run stylelint
        name: Stylelint
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"

  fe-tests:
    name: "Run Unit Tests / Core Features"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {} # GITHUB_TOKEN unused in this job
    defaults:
      run:
        working-directory: tasklist/client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
        name: Install dependencies
      - run: npm run test:ci
        name: Unit & Integration tests
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"

  fe-visual-regression-tests:
    name: "Visual regression tests / Core Features"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {} # GITHUB_TOKEN unused in this job
    container:
      image: mcr.microsoft.com/playwright:v1.54.2
      options: --user 1001:1000
    defaults:
      run:
        working-directory: tasklist/client
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install node dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build:visual-regression
      - name: Start server
        run: npm run start:visual-regression &
      - name: Run Playwright tests
        run: npm run test:visual
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tasklist-visual-regression-report
          path: tasklist/client/playwright-report/
          retention-days: 30
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"

  fe-a11y-tests:
    name: "a11y tests / Core Features"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {} # GITHUB_TOKEN unused in this job
    container:
      image: mcr.microsoft.com/playwright:v1.54.2
      options: --user 1001:1000
    defaults:
      run:
        working-directory: tasklist/client
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install node dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build
      - name: Start server
        run: npm run start:visual-regression &
      - name: Run A11y tests
        run: npm run test:a11y
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tasklist-a11y-report
          path: tasklist/client/playwright-report/
          retention-days: 30
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
          user_description: "team-core-features"
